name: offlineminigames
description: "A new Flutter project for OfflineMiniGames."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for good coding practices
  flutter_lints: ^5.0.0

  # Flutter Launcher Icons for managing app launcher icons
  flutter_launcher_icons: ^0.9.2

# Flutter specific configurations
flutter:
  assets:
    - assets/images/lgoo.webp # Image asset for your app

  uses-material-design: true # To include Material Design icons in your app

  # Configure custom fonts if needed (you can add your fonts here)
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to the icon image for both platforms
